### PR TITLE
Additions and features

### PR DESCRIPTION
**Pull request by phikal**
I implemented a few features from the TODO file:
- Support for nested tags between content
- Usability as a command line argument, e.g. `jsml -c [file]`
- Better package integration
- Support user-specified output file

And general optimisation here and there. I had to add [an optparse libary](https://github.com/jfd/optparse-js), which makes up most of the commits new lines.

**Edit:** Forgot to mention that I added short-tags:

`tag` can be written with `t`, `attributes` with `a`, `text` with `T` and `children` with `c`. Longer tags have a higher priority.

### CODE REVIEW

**Comment by mjkaufer** [comment]
Looks awesome. Thanks for contributing!

**Comment by mjkaufer** [comment]
Hey @phikal - there are some problems with your PR.

Basically, some errors I noticed:
- The output HTML pages didn't tab anymore - nothing was indented
- Attributes for many elements weren't updating - there were lots of `id` attributes with no corresponding values in the rendered HTML, despite these values being outlined in the JSML

However, I really like how you organized the code and made it better from a command line view. There are just some errors with your modifications to the compiler that break stuff.

I would try reverting the major changes to the compiler - i.e., leave `handleArray` alone. What you did with the parser worked excellently. If you would send a new PR with the parser code, etc., we can integrate that and, then, we can work together on implementing things such as shortened tags, etc.

Also, I'd rather have the project called `JSML` as opposed to `JSMLC` - that's just personal preference, sorry.

Thanks again for your help!

**Comment by phikal** [comment]
I will do that, I realized I had a few uncommitted changes too. Be back soon.

**Comment by mjkaufer** [comment]
Awesome!

**Pull request merged**
