### PR TITLE
Additions and features - 3

### PR DESCRIPTION
**Pull request by phikal**
In this PR I added/changed:
- Badges in README
- Created `/doc/`
- Split language and syntax into separate file (`/doc/LANG.md`)
- Moved `/bin/compile.js` to `/lib/common.js`
- Renamed `index.js`'s `toJSML` to `parse`. (It's not really converting anything **to** JSML, so I thought it was appropriate)
- Let `parse/toJSML`'s `eval` be optional.
- Logo fixes.
- Evaluate statements into tags.
- Read file into tag.
- Occasional fixes and improvements.

And as always, complain if you want something removed or changed, and it will be done as soon as I get to it.

### CODE REVIEW

**Comment by mjkaufer** [comment]
The only problem I have is the new `eval` tag. I would remove this as, to me, it seems a bit redundant, as the user can do everything which the new `eval` tag allows through the plain old `text` tag. 

Otherwise, everything looks great. I like the modularization of the readmes, and the new `file` tag is also pretty awesome. 

Also, when you remove the `eval` stuff, you can up the `package.json` version to `1.0.9`, as I'll push this all to npm when you're done.

Thanks!

**Comment by phikal** [comment]
As far as i know you can't write `4 * 8 + 3` in a text tag and expect a `35`. But doesn't matter, going to remove it from the main branch for now as soon as I get to it.

**Comment by phikal** [comment]
Changed it. If you change your mind, the `eval` tag can still be found in https://github.com/phikal/JSML/tree/eval-tag.

**Comment by mjkaufer** [comment]
I just tested the arithmetic problem you mentioned with the latest version.

Running

``` JavaScript

var jsml = require('node-jsml')

jsml.toJSML("[{t:'p',T:3*3}]")
```

returned 

``` HTML
<!DOCTYPE html>
<html>
    <p>9</p>
</html>
```

which is correct.

Everything else looks awesome, though. Merging now.

**Comment by phikal** [comment]
or now you would have to use `parse` instead of `toJSML`

**Pull request merged**
