### PR TITLE
Fixed TODO.md link

### PR DESCRIPTION
**Pull request by 2016rshah**
The link was broken because it was a relative path.

### CODE REVIEW

**Comment by phikal** [comment]
Wasn't it because the `TODO.md` was moved from the root directory to `/doc/`?

Shouldn't `/doc/TODO.md` be enough?

**Comment by 2016rshah** [comment]
I'm not sure I just tried to click it and it didn't work so I found the actual file and put that link in. It should work this way unless there is a reason you do not want to use the full link?

**Comment by phikal** [comment]
The problem is that if the link were opend in a different repository that @mjkaufer's, it would still send you to his TODO.MD file instead of the repositories.

**Comment by 2016rshah** [comment]
How's this?

**Comment by phikal** [comment]
That's what I meant. No reason not to approve since it is broken after all.

**Comment by mjkaufer** [comment]
Should it be `doc/TODO.MD` instead of `/doc/TODO.MD`?

**Comment by 2016rshah** [comment]
Either will work because the README is inside the root directory for the repo.

**Comment by mjkaufer** [comment]
So it's fine for GitHub but, if someone tries to clone the repo locally and view the readme, it will not work. If you could fix all the links to relative links (no leading `/`), that would be great.

**Comment by 2016rshah** [comment]
I don't know who clicks links and expects them to work locally but for everybody out there who does it should work now haha

**Comment by mjkaufer** [comment]
Thanks

**Pull request merged**
